package com.revature;

import java.util.ArrayList;

import com.revature.models.Account;
import com.revature.models.Role;
import com.revature.models.User;
import com.revature.repositories.UserDao;

public class App {

	public static void main(String[] args) {
		
		User u1 = new User("Tester", "pass", Role.Admin, new ArrayList<Account>());
		
		UserDao ud = new UserDao();
		
		int returnedPk = ud.insert(u1);
		
		// test to see if the dummy user we inserted was persisted and returned
		// a primary key generated by the DB.
		System.out.println(returnedPk);

	}

}
