version: 0.2
# In the cae that this app was built & deployed via 
# CI/CD pipeline, you would provide this buildspec
phases:
  build:
    commands:
      - java -version
      - mvn clean package
artifacts:
  files:
    - 'Dockerfile'
    - target/RestApi-0.0.1-SNAPSHOT.jar