package com.revature.models;

import java.util.ArrayList;
import java.util.List;

public class Student {
	
	private static int globalId = 1000; // everytime a student is instantiated I will increase this by 1.
	
	// firstname
	// lastname
	// gradeYear
	// studentId 
	// List of Courses
	// tuition balance
	private String firstName;
	private String lastName;
	private int gradeYear; // 1 - Freshman , 2- Sophomore 
	private String studentId; // we are concatenating the grade year to an autogenerated id
	private List<Course> courses = new ArrayList<Course>();
	
	// here we are declaring a DYNAMIC datastrcuture and inferring generics.
	// ArrayLists allow we to add and remove with ease
	private double tuitionBalance = 0;

	public Student(String firstName, String lastName, int gradeYear) {
		super();
		this.firstName = firstName;
		this.lastName = lastName;
		this.gradeYear = gradeYear;
		
		// call setStudentId()
		
	}
	
	
	
	// first student - > 21001
	// second student (senior) -> 41002 
	
	
	// setStudentId()
	
	// enroll()
	
	// viewBalance()
	
	// payTuition()
	
	// showStatus() 
	
	
	
	

}
